Fix compilation (m_misc.o: undefined reference to mus_extend_volume)
Its definition in e6y.c and use in SDL/i_sound.c in r3363 both depend on
_WIN32, so do the same for its use in m_misc.c and declaration in e6y.h.